version: '3'

tasks:
  dev.local:
    cmds:
      - go run cmd/www/main.go -config ./config/config.local.yaml
  # docker for local dev
  docker.up:
    preconditions:
      - test -f ./deploy/docker-compose.local.yaml
    cmds:
      - docker compose -f ./deploy/docker-compose.local.yaml up -d
  docker.down:
    preconditions:
      - test -f ./deploy/docker-compose.local.yaml
    cmds:
      - docker compose -f ./deploy/docker-compose.local.yaml down -v
  # sqlc
  sqlc.generate:
    cmds:
      - sqlc generate