version: "3"

includes:
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend
  deploy:
    taskfile: ./deploy/Taskfile.yaml
    dir: ./deploy

tasks:
  start.local:
    deps: [deploy:local.up, backend:dev, frontend.dev]
  frontend.dev:
    dir: ./frontend
    cmds:
      - pnpm run dev
