version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - wsl
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
issues:
  fix: true
  new: true
