version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - wsl
    - revive
    # TODO remove
    - lll
  settings:
    tagliatelle:
      case:
        rules:
          json: snake

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
