with-expecter: true
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
packages:
  github.com/cairon666/vkr-backend/internal/services/role_service:
    interfaces:
      RoleRepos:
        config:
          dir: "internal/services/role_service/mocks"
          outpkg: "mocks"
