version: "3.3"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - psql-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - vkr-network
  migrations:
    build:
      context: ../backend/migrations
      dockerfile: Dockerfile
    container_name: vkr-migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: /migrations
      GOOSE_DBSTRING: postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
      GOOSE_DB_HOST: postgres
      GOOSE_DB_PORT: 5432
      GOOSE_DB_USER: postgres
    depends_on:
      postgres:
        condition: service_started
    networks:
      - vkr-network
    restart: "no"
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis-vol:/data
    networks:
      - vkr-network

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      # Автоматическая настройка при первом запуске
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password123
      DOCKER_INFLUXDB_INIT_ORG: health-analytics
      DOCKER_INFLUXDB_INIT_BUCKET: health-data
      DOCKER_INFLUXDB_INIT_RETENTION: 8760h
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: dev-token-for-local-development-only
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - vkr-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - vkr-network

volumes:
  psql-vol:
  redis-vol:
  influxdb-data:
  influxdb-config:
  pgadmin-data:

networks:
  vkr-network:
    driver: bridge
